// Generated by CoffeeScript 1.6.2
var cube, filename, fs, square, _fn, _i, _len, _ref;

square = function(x) {
  return x * x;
};

cube = function(x) {
  return x * x * x;
};

fs = require('fs');

_ref = ['a', 'b', 'c'];
_fn = function(filename) {
  return function() {
    return fs.readFile(filename, function(err, contents) {
      return compile(filename, contents.toString());
    });
  };
};
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  filename = _ref[_i];
  _fn(filename);
}
