// Generated by CoffeeScript 1.6.2
(function() {
  var ChosenTicketModel;

  ChosenTicketModel = (function() {
    var _this = this;

    function ChosenTicketModel() {}

    ChosenTicketModel.tickets = [
      {
        name: "Economy",
        price: 199.95,
        name: "Business",
        price: 449.22,
        name: "First Class",
        price: 1199.99
      }
    ];

    ChosenTicketModel.chosenTicket = ko.observable();

    ChosenTicketModel.resetTicket = function() {
      return ChosenTicketModel.chosenTicket(null);
    };

    return ChosenTicketModel;

  }).call(this);

  $(function() {
    return ko.applyBindings(new ChosenTicketModel());
  });

}).call(this);
