// Generated by CoffeeScript 1.6.2
var ChosenTicketModel;

ChosenTicketModel = (function() {
  function ChosenTicketModel() {
    var _this = this;

    this.tickets = [
      {
        name: "Economy",
        price: 199.95
      }, {
        name: "Business",
        price: 449.22
      }, {
        name: "First Class",
        price: 1199.99
      }
    ];
    this.chosenTicket = ko.observable();
    this.resetTicket = function() {
      return _this.chosenTicket(null);
    };
  }

  return ChosenTicketModel;

})();
